"""Persistence boundary for background page import jobs."""

from typing import Protocol

from talkpath.domain.page_import import ImportJob, PageStatus


class PageImportRepository(Protocol):
    def create_job(self, job: ImportJob) -> ImportJob: ...
    def get_job(self, job_id: str) -> ImportJob | None: ...
    def list_jobs(self, lesson_id: str | None = None) -> list[ImportJob]: ...
    def claim(self, page_id: str) -> bool: ...
    def finish(
        self,
        page_id: str,
        status: PageStatus,
        error_code: str | None = None,
        error_message: str | None = None,
    ) -> ImportJob: ...
    def retry(self, page_id: str, operation_id: str) -> ImportJob: ...
    def reconcile(self, page_id: str, status: PageStatus) -> ImportJob: ...
